version: "3.8"

services:
  db:
    container_name: HealthISBachelor
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: HealthIS
      MYSQL_USER: groman
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
    restart: unless-stopped

  postgres_db:
    container_name: HealthIS_Users
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: HealthISUsers
      POSTGRES_USER: groman
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
  postgres_data: